import { RefObject } from "react"
import { ChevronIcon } from "./Icons"
import { CountPrice, RollingNumber } from "./MotionText"

export function AppFooter({ footerRef, itemCount, cupCount, total, limit, barHidden, loading, onCheckout }: { footerRef: RefObject<HTMLElement | null>; itemCount: number; cupCount: number; total: number; limit: number; barHidden: boolean; loading: boolean; onCheckout: () => void }) {
  return <>
    <footer className="app-footer" ref={footerRef}><div className="footer-content"><div className="footer-col footer-logo-col"><img src="/assets/footer/pickupcoffee-vertical.svg" alt="Pickup Coffee" className="footer-logo" /></div><div className="footer-col footer-nav-col"><nav className="footer-socials" aria-label="Social media links"><a href="https://x.com/pickupcoffeeph" target="_blank" rel="noopener noreferrer" aria-label="X (Twitter)"><img src="/assets/footer/x.svg" alt="" /></a><a href="https://www.instagram.com/pickupcoffeeph/" target="_blank" rel="noopener noreferrer" aria-label="Instagram"><img src="/assets/footer/instagram.svg" alt="" /></a><a href="https://www.youtube.com/@pickupcoffeeph" target="_blank" rel="noopener noreferrer" aria-label="YouTube"><img src="/assets/footer/youtube.svg" alt="" /></a><a href="https://www.tiktok.com/@pickupcoffee%20" target="_blank" rel="noopener noreferrer" aria-label="TikTok"><img src="/assets/footer/tiktok.svg" alt="" /></a></nav><div className="footer-copyright"><span className="footer-copyright-c">&copy;</span><img src="/assets/footer/pickupcoffee-horizontal.svg" alt="Pickup Coffee" className="footer-logo-horizontal" /><span className="footer-copyright-text">all rights reserved</span></div></div><div className="footer-col footer-news-col footer-news-col--desktop"><h3 className="footer-news-title">XADER LAGGUI</h3><p className="footer-news-subtitle">Aspiring Web Developer</p><button className="footer-news-btn" onClick={() => window.open("https://xaderlaggui.vercel.app", "_blank")}>My Portfolio</button></div></div></footer>
    {itemCount > 0 && <aside className={`order-bar active ${limit ? "at-limit" : ""} ${barHidden ? "bar-hidden" : ""}`}><div className="order-bar-inner"><div className={`cup-progress ${limit ? "limit-shake" : ""}`} aria-hidden="true">{Array.from({ length: 5 }).map((_, index) => <i className={index < cupCount ? "filled" : ""} key={index} />)}</div><div className="order-copy"><span id="order-bar-label">YOUR ORDER</span><strong aria-live="polite" aria-atomic="true">{limit ? "Max 5 cups" : <><RollingNumber value={itemCount} /> {itemCount === 1 ? "item" : "items"} · <CountPrice value={total} /></>}</strong></div><button className="checkout-button" onClick={onCheckout} type="button" disabled={loading}>{loading ? <span className="loading-dots" role="status"><i /><i /><i /></span> : <span className="price-crossfade">Checkout · <CountPrice value={total} /></span>}<ChevronIcon /></button></div></aside>}
  </>
}