import { Coffee } from "./types"
import blackCoffeeImg from "./assets/brewed-coffee.png"
export const coffees: Coffee[] = [
  {
    id: 1,
    name: "Latte",
    description: "Smooth espresso blended with fresh milk for a creamy, balanced cup.",
    detail: "Espresso · fresh milk",
    price: 75,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Latte_1024x1024_61a8cb3af8_7f4a391cee.png",
    tone: "rose",
  }, {
    id: 2,
    name: "Americano",
    description: "Bold double espresso softened with water for a clean, rich coffee.",
    detail: "Double espresso · water",
    price: 50,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Americano_1024x1024_7b202158ec_6ec9c51f27.png",
    tone: "rose",
  }, {
    id: 3,
    name: "Black Coffee",
    description: "Freshly brewed black coffee with a deep aroma and full-bodied finish.",
    detail: "Freshly brewed · hot",
    price: 65,
    image: blackCoffeeImg,
    tone: "rose",
  }, {
    id: 4,
    name: "Kape Kastila",
    description: "Leche condensada with creamy milk and rich espresso. Also available hot.",
    detail: "Condensed milk · espresso",
    price: 75,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/signatures_kape_kastila_52c8296c39_2b453f1af6.png",
    tone: "gold",
  }, {
    id: 5,
    name: "Caramel Macchiato",
    description: "Rich espresso layered with creamy milk and a sweet caramel finish.",
    detail: "Espresso · caramel",
    price: 89,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/signatures_caramel_macchiato_83ede1a994_123679384e.png",
    tone: "gold",
  }, {
    id: 6,
    name: "Pickup Crème Latte",
    description: "A smooth, creamy latte finished with Pickup’s signature crème.",
    detail: "Espresso · milk · crème",
    price: 95,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/signatures_creme_latte_9b2aaa6b4d_a5a0f7cad1.png",
    tone: "rose",
  },  {
    id: 7,
    name: "White Mocha Latte",
    description: "White chocolate with creamy milk and rich espresso, also available hot.",
    detail: "White chocolate · espresso",
    price: 89,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/signatures_white_mocha_latte_5be6ab542b_29998d088f.png",
    tone: "rose",
  }, {
    id: 8,
    name: "Cappuccino",
    description: "Rich espresso with hot steamed milk and foam.",
    detail: "Espresso · steamed milk",
    price: 75,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Capuccino_1024x1024_5f9eddf1a2_50d0058cfb.png",
    tone: "rose",
  }, {
    id: 9,
    name: "Brown Sugar Latte",
    description: "Rich espresso with creamy milk and brown molasses syrup, also available hot.",
    detail: "Espresso · brown sugar",
    price: 79,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Kape_Mestizo_1024x1024_48acf7699b_b3cac3d4a6.png",
    tone: "gold",
  }, {
    id: 10,
    name: "Sea Salt Biscoff Latte",
    description: "Rich espresso with creamy milk, Biscoff cookie bits, and sea salt cream mousse.",
    detail: "Espresso · Biscoff · sea salt",
    price: 115,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/Biscoff_Latte_5937c20daa_8add35fc0f.png",
    tone: "gold",
  }, {
    id: 11,
    name: "Sea Salt Latte",
    description: "Rich espresso with creamy milk, topped with sea salt milk foam.",
    detail: "Espresso · sea salt foam",
    price: 89,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Iced_Sea_Salt_Latte_1024x1024_7da7890cc3_f5ead4030e.png",
    tone: "rose",
  }, {
    id: 12,
    name: "Vietnamese Latte",
    description: "A strong blend of rich espresso with leche condensada.",
    detail: "Espresso · condensed milk",
    price: 79,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Iced_Vietnamese_Latte_1024x1024_56c7d8a77c_d3469985e5.png",
    tone: "gold",
  }, {
    id: 13,
    name: "Vanilla Latte",
    description: "A velvety blend of creamy vanilla with milk and rich espresso, also available hot.",
    detail: "Espresso · vanilla · milk",
    price: 85,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Iced_Vanilla_1024x1024_daa87a6e40_1f40ffe646.png",
    tone: "rose",
  }, {
    id: 14,
    name: "Dark Chocolate Latte",
    description: "Dark chocolate with creamy milk and rich espresso, also available hot.",
    detail: "Espresso · dark chocolate",
    price: 85,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Dark_Choco_1024x1024_b1d658f966_e8d1e05576.png",
    tone: "gold",
  }, {
    id: 15,
    name: "Flat White",
    description: "Rich espresso with hot steamed milk.",
    detail: "Espresso · steamed milk",
    price: 75,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/Flat_White_cfe4c5ac4e_106dda3f74.png",
    tone: "rose",
  }, {
    id: 16,
    name: "Espresso",
    description: "A double shot of rich espresso.",
    detail: "Double espresso",
    price: 30,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Espresso_1024x1024_09b90a600f_cea8ee9c4e.png",
    tone: "rose",
  }, {
    id: 17,
    name: "Hazelnut Latte",
    description: "Rich espresso with creamy milk and Nutella, also available hot.",
    detail: "Espresso · hazelnut · milk",
    price: 95,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Nutellate_1024x1024_6843d4394b_42828bca1c.png",
    tone: "gold",
  }, {
    id: 18,
    name: "Hot Pistachio Latte",
    description: "Hot steamed milk with rich pistachio and bold espresso.",
    detail: "Espresso · pistachio",
    price: 119,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_POS_APP_PICKAROO_PISTACHIO_AGGREG_ADDON_hotpistlatte_f0f92e3ece_594adc4375.png",
    tone: "gold",
  }, {
    id: 19,
    name: "Iced Pistachio Latte",
    description: "Creamy milk with rich pistachio and bold espresso, over ice.",
    detail: "Espresso · pistachio · iced",
    price: 119,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_POS_APP_PICKAROO_PISTACHIO_AGGREG_ADDON_PIST_98a44b1fe9_670aaf4816.png",
    tone: "gold",
  }, {
    id: 20,
    name: "White Mocha Frappe",
    description: "Rich espresso and white chocolate blended with creamy milk and ice.",
    detail: "Espresso · white chocolate · frappe",
    price: 109,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_GRAB_WHITE_MOCHA_FRAPPE_46bfc25d35_ed272154fc.png",
    tone: "rose",
  }, {
    id: 21,
    name: "Kape Kastila Frappe",
    description: "Rich espresso and leche condensada blended with creamy milk and ice.",
    detail: "Espresso · condensed milk · frappe",
    price: 99,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_GRAB_KK_Frappe_b4886a7378_27cdd5f07c.png",
    tone: "gold",
  }, {
    id: 22,
    name: "Cafe Mocha Chip Frappe",
    description: "Rich espresso and dark chocolate blended with chocolate chips and creamy milk.",
    detail: "Espresso · chocolate · frappe",
    price: 115,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Mocha_Chip_Frappe_344a07d5c8_979b8fe804.png",
    tone: "gold",
  }, {
    id: 23,
    name: "Brown Sugar Coffee Jelly Frappe",
    description: "Rich espresso and brown molasses syrup blended with creamy milk and coffee jelly.",
    detail: "Espresso · coffee jelly · frappe",
    price: 129,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_GRAB_BROWN_SUGAR_COFFEE_JELLY_FRAPPE_aec2c90ecd_a87b8a7522.png",
    tone: "gold",
  }, {
    id: 24,
    name: "Caramel Frappe",
    description: "Rich espresso and buttery caramel blended with creamy milk and ice.",
    detail: "Espresso · caramel · frappe",
    price: 99,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_GRAB_Caramel_Frappe_b9c9aa01c7_9a5dc45b74.png",
    tone: "gold",
  }, {
    id: 25,
    name: "Protein Latte",
    description: "Bold espresso with creamy milk and a boost of Wheyl protein, over ice.",
    detail: "Espresso · protein · iced",
    price: 145,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/protein_latte_ff35aad77d_6759b817f1.png",
    tone: "rose",
  }, {
    id: 26,
    name: "Sugar-Free Sweet Americano",
    description: "Rich espresso with water and sugar-free sweetener, over ice.",
    detail: "Espresso · sugar-free · iced",
    price: 59,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/SF_Americano_1_d9d32845e0_4424b4fda8.png",
    tone: "rose",
  }, {
    id: 27,
    name: "Auro Tsokolatte",
    description: "Creamy milk with Auro cacao powder and espresso, over ice. Also available hot.",
    detail: "Espresso · cacao · milk",
    price: 99,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/IMG_1903_6940f23820.JPG",
    tone: "gold",
  }, {
    id: 28,
    name: "Peanut Brittle Latte",
    description: "Creamy milk with real peanut brittle spread and espresso, over ice. Also available hot.",
    detail: "Espresso · peanut brittle",
    price: 109,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/IMG_1904_991ff4d45e.JPG",
    tone: "gold",
  }, {
    id: 29,
    name: "Chocolate Croissant",
    description: "A flaky and buttery croissant, rolled with dark chocolate.",
    detail: "Pickup Bites · pastry",
    price: 89,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Choco_Croissant_1024x1024_1faa5601cd_58520d3c5a.png",
    tone: "gold",
  }, {
    id: 30,
    name: "Classic Choco Cookie",
    description: "An indulgent cookie with dark chocolate chunks, seasoned with sea salt.",
    detail: "Pickup Bites · cookie",
    price: 109,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Classic_Choco_Cookie_1024x1024_762f9e6d87_245a08b622.png",
    tone: "gold",
  }, {
    id: 31,
    name: "Classic Croissant",
    description: "A flaky and buttery croissant.",
    detail: "Pickup Bites · pastry",
    price: 80,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_Classic_Croissant_1024x1024_9392d51dd3_428d62c84e.png",
    tone: "gold",
  }, {
    id: 32,
    name: "Triple Chocolate Cookie",
    description: "An indulgent chocolate cookie with white and dark chocolate chunks.",
    detail: "Pickup Bites · cookie",
    price: 119,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_GRAB_Triple_Chocolate_Cookie_2a350da939_74b4a14d12.png",
    tone: "gold",
  }, {
    id: 33,
    name: "Oatmeal Cookie",
    description: "A chewy oatmeal cookie with a sprinkle of cinnamon.",
    detail: "Pickup Bites · cookie",
    price: 99,
    image: "https://d1r9lpkrafbxq0.cloudfront.net/strapi-cms-readable-media/menu_GRAB_Oatmeal_cookie_db0cbf9979_bb7604f960.png",
    tone: "gold",
  },
]
export const times = ["ASAP", "08:15 AM", "08:30 AM", "08:45 AM", "09:00 AM"]
